"""Data container for in game blocks and items."""

# Probably 1.8 version.
BLOCK = {
    0: {0: {'name': 'Air', 'properties': {}}},
    1: {0: {'name': 'Stone', 'properties': {}},
        1: {'name': 'Granite', 'properties': {}},
        2: {'name': 'Polished Granite', 'properties': {}},
        3: {'name': 'Diorite', 'properties': {}},
        4: {'name': 'Polished Diorite', 'properties': {}},
        5: {'name': 'Andesite', 'properties': {}},
        6: {'name': 'Polished Andesite', 'properties': {}}},
    2: {0: {'name': 'Grass', 'properties': {}}},
    3: {0: {'name': 'Dirt', 'properties': {}},
        1: {'name': 'Coarse Dirt', 'properties': {}},
        2: {'name': 'Podzol', 'properties': {}}},
    4: {0: {'name': 'Cobblestone', 'properties': {}}},
    5: {0: {'name': 'Wooden Plank (Oak)', 'properties': {}},
        1: {'name': 'Wooden Plank (Spruce)', 'properties': {}},
        2: {'name': 'Wooden Plank (Birch)', 'properties': {}},
        3: {'name': 'Wooden Plank (Jungle)', 'properties': {}},
        4: {'name': 'Wooden Plank (Acacia)', 'properties': {}},
        5: {'name': 'Wooden Plank (Dark Oak)', 'properties': {}}},
    6: {0: {'name': 'Sapling (Oak)', 'properties': {}},
        1: {'name': 'Sapling (Spruce)', 'properties': {}},
        2: {'name': 'Sapling (Birch)', 'properties': {}},
        3: {'name': 'Sapling (Jungle)', 'properties': {}},
        4: {'name': 'Sapling (Acacia)', 'properties': {}},
        5: {'name': 'Sapling (Dark Oak)', 'properties': {}}},
    7: {0: {'name': 'Bedrock', 'properties': {}}},
    8: {0: {'name': 'Water', 'properties': {}}},
    9: {0: {'name': 'Water (No Spread)', 'properties': {}}},
    10: {0: {'name': 'Lava', 'properties': {}}},
    11: {0: {'name': 'Lava (No Spread)', 'properties': {}}},
    12: {0: {'name': 'Sand', 'properties': {}},
         1: {'name': 'Red Sand', 'properties': {}}},
    13: {0: {'name': 'Gravel', 'properties': {}}},
    14: {0: {'name': 'Gold Ore', 'properties': {}}},
    15: {0: {'name': 'Iron Ore', 'properties': {}}},
    16: {0: {'name': 'Coal Ore', 'properties': {}}},
    17: {0: {'name': 'Wood (Oak)', 'properties': {}},
         1: {'name': 'Wood (Spruce)', 'properties': {}},
         2: {'name': 'Wood (Birch)', 'properties': {}},
         3: {'name': 'Wood (Jungle)', 'properties': {}},
         4: {'name': 'Wood (Oak 4)', 'properties': {}},
         5: {'name': 'Wood (Oak 5)', 'properties': {}}},
    18: {0: {'name': 'Leaves (Oak)', 'properties': {}},
         1: {'name': 'Leaves (Spruce)', 'properties': {}},
         2: {'name': 'Leaves (Birch)', 'properties': {}},
         3: {'name': 'Leaves (Jungle)', 'properties': {}}},
    19: {0: {'name': 'Sponge', 'properties': {}},
         1: {'name': 'Wet Sponge', 'properties': {}}},
    20: {0: {'name': 'Glass', 'properties': {}}},
    21: {0: {'name': 'Lapis Lazuli Ore', 'properties': {}}},
    22: {0: {'name': 'Lapis Lazuli Block', 'properties': {}}},
    23: {0: {'name': 'Dispenser', 'properties': {}}},
    24: {0: {'name': 'Sandstone', 'properties': {}},
         1: {'name': 'Sandstone (Chiseled)', 'properties': {}},
         2: {'name': 'Sandstone (Smooth)', 'properties': {}}},
    25: {0: {'name': 'Note Block', 'properties': {}}},
    26: {0: {'name': 'Bed (Block)', 'properties': {}}},
    27: {0: {'name': 'Rail (Powered)', 'properties': {}}},
    28: {0: {'name': 'Rail (Detector)', 'properties': {}}},
    29: {0: {'name': 'Sticky Piston', 'properties': {}}},
    30: {0: {'name': 'Cobweb', 'properties': {}}},
    31: {0: {'name': 'Tall Grass (Dead Shrub)', 'properties': {}},
         1: {'name': 'Tall Grass', 'properties': {}},
         2: {'name': 'Tall Grass (Fern)', 'properties': {}}},
    32: {0: {'name': 'Dead Shrub', 'properties': {}}},
    33: {0: {'name': 'Piston', 'properties': {}}},
    34: {0: {'name': 'Piston (Head)', 'properties': {}}},
    35: {0: {'name': 'Wool', 'properties': {}},
         1: {'name': 'Orange Wool', 'properties': {}},
         2: {'name': 'Magenta Wool', 'properties': {}},
         3: {'name': 'Light Blue Wool', 'properties': {}},
         4: {'name': 'Yellow Wool', 'properties': {}},
         5: {'name': 'Lime Wool', 'properties': {}},
         6: {'name': 'Pink Wool', 'properties': {}},
         7: {'name': 'Gray Wool', 'properties': {}},
         8: {'name': 'Light Gray Wool', 'properties': {}},
         9: {'name': 'Cyan Wool', 'properties': {}},
         10: {'name': 'Purple Wool', 'properties': {}},
         11: {'name': 'Blue Wool', 'properties': {}},
         12: {'name': 'Brown Wool', 'properties': {}},
         13: {'name': 'Green Wool', 'properties': {}},
         14: {'name': 'Red Wool', 'properties': {}},
         15: {'name': 'Black Wool', 'properties': {}}},
    36: {0: {'name': 'Piston (Moving)', 'properties': {}}},
    37: {0: {'name': 'Dandelion', 'properties': {}}},
    38: {0: {'name': 'Poppy', 'properties': {}},
         1: {'name': 'Blue Orchid', 'properties': {}},
         2: {'name': 'Allium', 'properties': {}},
         3: {'name': 'Azure Bluet', 'properties': {}},
         4: {'name': 'Red Tulip', 'properties': {}},
         5: {'name': 'Orange Tulip', 'properties': {}},
         6: {'name': 'White Tulip', 'properties': {}},
         7: {'name': 'Pink Tulip', 'properties': {}},
         8: {'name': 'Oxeye Daisy', 'properties': {}}},
    39: {0: {'name': 'Brown Mushroom', 'properties': {}}},
    40: {0: {'name': 'Red Mushroom', 'properties': {}}},
    41: {0: {'name': 'Block of Gold', 'properties': {}}},
    42: {0: {'name': 'Block of Iron', 'properties': {}}},
    43: {0: {'name': 'Stone Slab (Double)', 'properties': {}},
         1: {'name': 'Sandstone Slab (Double)', 'properties': {}},
         2: {'name': 'Wooden Slab (Double)', 'properties': {}},
         3: {'name': 'Cobblestone Slab (Double)', 'properties': {}},
         4: {'name': 'Brick Slab (Double)', 'properties': {}},
         5: {'name': 'Stone Brick Slab (Double)', 'properties': {}},
         6: {'name': 'Nether Brick Slab (Double)', 'properties': {}},
         7: {'name': 'Quartz Slab (Double)', 'properties': {}},
         8: {'name': 'Smooth Stone Slab (Double)', 'properties': {}},
         9: {'name': 'Smooth Sandstone Slab (Double)', 'properties': {}}},
    44: {0: {'name': 'Stone Slab', 'properties': {}},
         1: {'name': 'Sandstone Slab', 'properties': {}},
         2: {'name': 'Wooden Slab', 'properties': {}},
         3: {'name': 'Cobblestone Slab', 'properties': {}},
         4: {'name': 'Brick Slab', 'properties': {}},
         5: {'name': 'Stone Brick Slab', 'properties': {}},
         6: {'name': 'Nether Brick Slab', 'properties': {}},
         7: {'name': 'Quartz Slab', 'properties': {}}},
    45: {0: {'name': 'Brick', 'properties': {}}},
    46: {0: {'name': 'TNT', 'properties': {}}},
    47: {0: {'name': 'Bookshelf', 'properties': {}}},
    48: {0: {'name': 'Moss Stone', 'properties': {}}},
    49: {0: {'name': 'Obsidian', 'properties': {}}},
    50: {0: {'name': 'Torch', 'properties': {}}},
    51: {0: {'name': 'Fire', 'properties': {}}},
    52: {0: {'name': 'Mob Spawner', 'properties': {}}},
    53: {0: {'name': 'Wooden Stairs (Oak)', 'properties': {}}},
    54: {0: {'name': 'Chest', 'properties': {}}},
    55: {0: {'name': 'Redstone Wire', 'properties': {}}},
    56: {0: {'name': 'Diamond Ore', 'properties': {}}},
    57: {0: {'name': 'Block of Diamond', 'properties': {}}},
    58: {0: {'name': 'Workbench', 'properties': {}}},
    59: {0: {'name': 'Wheat (Crop)', 'properties': {}}},
    60: {0: {'name': 'Farmland', 'properties': {}}},
    61: {0: {'name': 'Furnace', 'properties': {}}},
    62: {0: {'name': 'Furnace (Smelting)', 'properties': {}}},
    63: {0: {'name': 'Sign (Block)', 'properties': {}}},
    64: {0: {'name': 'Wood Door (Block)', 'properties': {}}},
    65: {0: {'name': 'Ladder', 'properties': {}}},
    66: {0: {'name': 'Rail', 'properties': {}}},
    67: {0: {'name': 'Cobblestone Stairs', 'properties': {}}},
    68: {0: {'name': 'Sign (Wall Block)', 'properties': {}}},
    69: {0: {'name': 'Lever', 'properties': {}}},
    70: {0: {'name': 'Stone Pressure Plate', 'properties': {}}},
    71: {0: {'name': 'Iron Door (Block)', 'properties': {}}},
    72: {0: {'name': 'Wooden Pressure Plate', 'properties': {}}},
    73: {0: {'name': 'Redstone Ore', 'properties': {}}},
    74: {0: {'name': 'Redstone Ore (Glowing)', 'properties': {}}},
    75: {0: {'name': 'Redstone Torch (Off)', 'properties': {}}},
    76: {0: {'name': 'Redstone Torch', 'properties': {}}},
    77: {0: {'name': 'Button (Stone)', 'properties': {}}},
    78: {0: {'name': 'Snow', 'properties': {}}},
    79: {0: {'name': 'Ice', 'properties': {}}},
    80: {0: {'name': 'Snow Block', 'properties': {}}},
    81: {0: {'name': 'Cactus', 'properties': {}}},
    82: {0: {'name': 'Clay Block', 'properties': {}}},
    83: {0: {'name': 'Sugar Cane (Block)', 'properties': {}}},
    84: {0: {'name': 'Jukebox', 'properties': {}}},
    85: {0: {'name': 'Fence (Oak)', 'properties': {}}},
    86: {0: {'name': 'Pumpkin', 'properties': {}}},
    87: {0: {'name': 'Netherrack', 'properties': {}}},
    88: {0: {'name': 'Soul Sand', 'properties': {}}},
    89: {0: {'name': 'Glowstone', 'properties': {}}},
    90: {0: {'name': 'Portal', 'properties': {}}},
    91: {0: {'name': 'Jack-O-Lantern', 'properties': {}}},
    92: {0: {'name': 'Cake (Block)', 'properties': {}}},
    93: {0: {'name': 'Redstone Repeater (Block Off)', 'properties': {}}},
    94: {0: {'name': 'Redstone Repeater (Block On)', 'properties': {}}},
    95: {0: {'name': 'Stained Glass (White)', 'properties': {}},
         1: {'name': 'Stained Glass (Orange)', 'properties': {}},
         2: {'name': 'Stained Glass (Magenta)', 'properties': {}},
         3: {'name': 'Stained Glass (Light Blue)', 'properties': {}},
         4: {'name': 'Stained Glass (Yellow)', 'properties': {}},
         5: {'name': 'Stained Glass (Lime)', 'properties': {}},
         6: {'name': 'Stained Glass (Pink)', 'properties': {}},
         7: {'name': 'Stained Glass (Gray)', 'properties': {}},
         8: {'name': 'Stained Glass (Light Grey)', 'properties': {}},
         9: {'name': 'Stained Glass (Cyan)', 'properties': {}},
         10: {'name': 'Stained Glass (Purple)', 'properties': {}},
         11: {'name': 'Stained Glass (Blue)', 'properties': {}},
         12: {'name': 'Stained Glass (Brown)', 'properties': {}},
         13: {'name': 'Stained Glass (Green)', 'properties': {}},
         14: {'name': 'Stained Glass (Red)', 'properties': {}},
         15: {'name': 'Stained Glass (Black)', 'properties': {}}},
    96: {0: {'name': 'Trapdoor', 'properties': {}}},
    97: {0: {'name': 'Monster Egg (Stone)', 'properties': {}},
         1: {'name': 'Monster Egg (Cobblestone)', 'properties': {}},
         2: {'name': 'Monster Egg (Stone Brick)', 'properties': {}},
         3: {'name': 'Monster Egg (Mossy Stone Brick)', 'properties': {}},
         4: {'name': 'Monster Egg (Cracked Stone)', 'properties': {}},
         5: {'name': 'Monster Egg (Chiseled Stone)', 'properties': {}}},
    98: {0: {'name': 'Stone Bricks', 'properties': {}},
         1: {'name': 'Mossy Stone Bricks', 'properties': {}},
         2: {'name': 'Cracked Stone Bricks', 'properties': {}},
         3: {'name': 'Chiseled Stone Brick', 'properties': {}}},
    99: {0: {'name': 'Brown Mushroom (Block)', 'properties': {}}},
    100: {0: {'name': 'Red Mushroom (Block)', 'properties': {}}},
    101: {0: {'name': 'Iron Bars', 'properties': {}}},
    102: {0: {'name': 'Glass Pane', 'properties': {}}},
    103: {0: {'name': 'Melon (Block)', 'properties': {}}},
    104: {0: {'name': 'Pumpkin Vine', 'properties': {}}},
    105: {0: {'name': 'Melon Vine', 'properties': {}}},
    106: {0: {'name': 'Vines', 'properties': {}}},
    107: {0: {'name': 'Fence Gate (Oak)', 'properties': {}}},
    108: {0: {'name': 'Brick Stairs', 'properties': {}}},
    109: {0: {'name': 'Stone Brick Stairs', 'properties': {}}},
    110: {0: {'name': 'Mycelium', 'properties': {}}},
    111: {0: {'name': 'Lily Pad', 'properties': {}}},
    112: {0: {'name': 'Nether Brick', 'properties': {}}},
    113: {0: {'name': 'Nether Brick Fence', 'properties': {}}},
    114: {0: {'name': 'Nether Brick Stairs', 'properties': {}}},
    115: {0: {'name': 'Nether Wart', 'properties': {}}},
    116: {0: {'name': 'Enchantment Table', 'properties': {}}},
    117: {0: {'name': 'Brewing Stand (Block)', 'properties': {}}},
    118: {0: {'name': 'Cauldron (Block)', 'properties': {}}},
    119: {0: {'name': 'End Portal', 'properties': {}}},
    120: {0: {'name': 'End Portal Frame', 'properties': {}}},
    121: {0: {'name': 'End Stone', 'properties': {}}},
    122: {0: {'name': 'Dragon Egg', 'properties': {}}},
    123: {0: {'name': 'Redstone Lamp', 'properties': {}}},
    124: {0: {'name': 'Redstone Lamp (On)', 'properties': {}}},
    125: {0: {'name': 'Oak-Wood Slab (Double)', 'properties': {}},
          1: {'name': 'Spruce-Wood Slab (Double)', 'properties': {}},
          2: {'name': 'Birch-Wood Slab (Double)', 'properties': {}},
          3: {'name': 'Jungle-Wood Slab (Double)', 'properties': {}},
          4: {'name': 'Acacia Wood Slab (Double)', 'properties': {}},
          5: {'name': 'Dark Oak Wood Slab (Double)', 'properties': {}}},
    126: {0: {'name': 'Oak-Wood Slab', 'properties': {}},
          1: {'name': 'Spruce-Wood Slab', 'properties': {}},
          2: {'name': 'Birch-Wood Slab', 'properties': {}},
          3: {'name': 'Jungle-Wood Slab', 'properties': {}},
          4: {'name': 'Acacia Wood Slab', 'properties': {}},
          5: {'name': 'Dark Oak Wood Slab', 'properties': {}}},
    127: {0: {'name': 'Cocoa Plant', 'properties': {}}},
    128: {0: {'name': 'Sandstone Stairs', 'properties': {}}},
    129: {0: {'name': 'Emerald Ore', 'properties': {}}},
    130: {0: {'name': 'Ender Chest', 'properties': {}}},
    131: {0: {'name': 'Tripwire Hook', 'properties': {}}},
    132: {0: {'name': 'Tripwire', 'properties': {}}},
    133: {0: {'name': 'Block of Emerald', 'properties': {}}},
    134: {0: {'name': 'Wooden Stairs (Spruce)', 'properties': {}}},
    135: {0: {'name': 'Wooden Stairs (Birch)', 'properties': {}}},
    136: {0: {'name': 'Wooden Stairs (Jungle)', 'properties': {}}},
    137: {0: {'name': 'Command Block', 'properties': {}}},
    138: {0: {'name': 'Beacon', 'properties': {}}},
    139: {0: {'name': 'Cobblestone Wall', 'properties': {}},
          1: {'name': 'Mossy Cobblestone Wall', 'properties': {}}},
    140: {0: {'name': 'Flower Pot (Block)', 'properties': {}}},
    141: {0: {'name': 'Carrot (Crop)', 'properties': {}}},
    142: {0: {'name': 'Potatoes (Crop)', 'properties': {}}},
    143: {0: {'name': 'Button (Wood)', 'properties': {}}},
    144: {0: {'name': 'Head Block (Skeleton)', 'properties': {}},
          1: {'name': 'Head Block (Wither)', 'properties': {}},
          2: {'name': 'Head Block (Zombie)', 'properties': {}},
          3: {'name': 'Head Block (Steve)', 'properties': {}},
          4: {'name': 'Head Block (Creeper)', 'properties': {}}},
    145: {0: {'name': 'Anvil', 'properties': {}},
          1: {'name': 'Anvil (Slightly Damaged)', 'properties': {}},
          2: {'name': 'Anvil (Very Damaged)', 'properties': {}}},
    146: {0: {'name': 'Trapped Chest', 'properties': {}}},
    147: {0: {'name': 'Weighted Pressure Plate (Light)', 'properties': {}}},
    148: {0: {'name': 'Weighted Pressure Plate (Heavy)', 'properties': {}}},
    149: {0: {'name': 'Redstone Comparator (Off)', 'properties': {}}},
    150: {0: {'name': 'Redstone Comparator (On)', 'properties': {}}},
    151: {0: {'name': 'Daylight Sensor', 'properties': {}}},
    152: {0: {'name': 'Block of Redstone', 'properties': {}}},
    153: {0: {'name': 'Nether Quartz Ore', 'properties': {}}},
    154: {0: {'name': 'Hopper', 'properties': {}}},
    155: {0: {'name': 'Quartz Block', 'properties': {}},
          1: {'name': 'Chiseled Quartz Block', 'properties': {}},
          2: {'name': 'Pillar Quartz Block', 'properties': {}}},
    156: {0: {'name': 'Quartz Stairs', 'properties': {}}},
    157: {0: {'name': 'Rail (Activator)', 'properties': {}}},
    158: {0: {'name': 'Dropper', 'properties': {}}},
    159: {0: {'name': 'Stained Clay (White)', 'properties': {}},
          1: {'name': 'Stained Clay (Orange)', 'properties': {}},
          2: {'name': 'Stained Clay (Magenta)', 'properties': {}},
          3: {'name': 'Stained Clay (Light Blue)', 'properties': {}},
          4: {'name': 'Stained Clay (Yellow)', 'properties': {}},
          5: {'name': 'Stained Clay (Lime)', 'properties': {}},
          6: {'name': 'Stained Clay (Pink)', 'properties': {}},
          7: {'name': 'Stained Clay (Gray)', 'properties': {}},
          8: {'name': 'Stained Clay (Light Gray)', 'properties': {}},
          9: {'name': 'Stained Clay (Cyan)', 'properties': {}},
          10: {'name': 'Stained Clay (Purple)', 'properties': {}},
          11: {'name': 'Stained Clay (Blue)', 'properties': {}},
          12: {'name': 'Stained Clay (Brown)', 'properties': {}},
          13: {'name': 'Stained Clay (Green)', 'properties': {}},
          14: {'name': 'Stained Clay (Red)', 'properties': {}},
          15: {'name': 'Stained Clay (Black)', 'properties': {}}},
    160: {0: {'name': 'Stained Glass Pane (White)', 'properties': {}},
          1: {'name': 'Stained Glass Pane (Orange)', 'properties': {}},
          2: {'name': 'Stained Glass Pane (Magenta)', 'properties': {}},
          3: {'name': 'Stained Glass Pane (Light Blue)', 'properties': {}},
          4: {'name': 'Stained Glass Pane (Yellow)', 'properties': {}},
          5: {'name': 'Stained Glass Pane (Lime)', 'properties': {}},
          6: {'name': 'Stained Glass Pane (Pink)', 'properties': {}},
          7: {'name': 'Stained Glass Pane (Gray)', 'properties': {}},
          8: {'name': 'Stained Glass Pane (Light Gray)', 'properties': {}},
          9: {'name': 'Stained Glass Pane (Cyan)', 'properties': {}},
          10: {'name': 'Stained Glass Pane (Purple)', 'properties': {}},
          11: {'name': 'Stained Glass Pane (Blue)', 'properties': {}},
          12: {'name': 'Stained Glass Pane (Brown)', 'properties': {}},
          13: {'name': 'Stained Glass Pane (Green)', 'properties': {}},
          14: {'name': 'Stained Glass Pane (Red)', 'properties': {}},
          15: {'name': 'Stained Glass Pane (Black)', 'properties': {}}},
    161: {0: {'name': 'Leaves (Acacia)', 'properties': {}},
          1: {'name': 'Leaves (Dark Oak)', 'properties': {}}},
    162: {0: {'name': 'Wood (Acacia Oak)', 'properties': {}},
          1: {'name': 'Wood (Dark Oak)', 'properties': {}}},
    163: {0: {'name': 'Wooden Stairs (Acacia)', 'properties': {}}},
    164: {0: {'name': 'Wooden Stairs (Dark Oak)', 'properties': {}}},
    165: {0: {'name': 'Slime Block', 'properties': {}}},
    166: {0: {'name': 'Barrier', 'properties': {}}},
    167: {0: {'name': 'Iron Trapdoor', 'properties': {}}},
    168: {0: {'name': 'Prismarine', 'properties': {}},
          1: {'name': 'Prismarine Bricks', 'properties': {}},
          2: {'name': 'Dark Prismarine', 'properties': {}}},
    169: {0: {'name': 'Sea Lantern', 'properties': {}}},
    170: {0: {'name': 'Hay Bale', 'properties': {}}},
    171: {0: {'name': 'Carpet (White)', 'properties': {}},
          1: {'name': 'Carpet (Orange)', 'properties': {}},
          2: {'name': 'Carpet (Magenta)', 'properties': {}},
          3: {'name': 'Carpet (Light Blue)', 'properties': {}},
          4: {'name': 'Carpet (Yellow)', 'properties': {}},
          5: {'name': 'Carpet (Lime)', 'properties': {}},
          6: {'name': 'Carpet (Pink)', 'properties': {}},
          7: {'name': 'Carpet (Grey)', 'properties': {}},
          8: {'name': 'Carpet (Light Gray)', 'properties': {}},
          9: {'name': 'Carpet (Cyan)', 'properties': {}},
          10: {'name': 'Carpet (Purple)', 'properties': {}},
          11: {'name': 'Carpet (Blue)', 'properties': {}},
          12: {'name': 'Carpet (Brown)', 'properties': {}},
          13: {'name': 'Carpet (Green)', 'properties': {}},
          14: {'name': 'Carpet (Red)', 'properties': {}},
          15: {'name': 'Carpet (Black)', 'properties': {}}},
    172: {0: {'name': 'Hardened Clay', 'properties': {}}},
    173: {0: {'name': 'Block of Coal', 'properties': {}}},
    174: {0: {'name': 'Packed Ice', 'properties': {}}},
    175: {0: {'name': 'Sunflower', 'properties': {}},
          1: {'name': 'Lilac', 'properties': {}},
          2: {'name': 'Double Tallgrass', 'properties': {}},
          3: {'name': 'Large Fern', 'properties': {}},
          4: {'name': 'Rose Bush', 'properties': {}},
          5: {'name': 'Peony', 'properties': {}}},
    176: {0: {'name': 'Standing Banner (Block)', 'properties': {}}},
    177: {0: {'name': 'Wall Banner (Block)', 'properties': {}}},
    178: {0: {'name': 'Inverted Daylight Sensor', 'properties': {}}},
    179: {0: {'name': 'Red Sandstone', 'properties': {}},
          1: {'name': 'Red Sandstone (Chiseled)', 'properties': {}},
          2: {'name': 'Red Sandstone (Smooth)', 'properties': {}}},
    180: {0: {'name': 'Red Sandstone Stairs', 'properties': {}}},
    181: {0: {'name': 'Red Sandstone Slab (Double)', 'properties': {}}},
    182: {0: {'name': 'Red Sandstone Slab', 'properties': {}}},
    183: {0: {'name': 'Fence Gate (Spruce)', 'properties': {}}},
    184: {0: {'name': 'Fence Gate (Birch)', 'properties': {}}},
    185: {0: {'name': 'Fence Gate (Jungle)', 'properties': {}}},
    186: {0: {'name': 'Fence Gate (Dark Oak)', 'properties': {}}},
    187: {0: {'name': 'Fence Gate (Acacia)', 'properties': {}}},
    188: {0: {'name': 'Fence (Spruce)', 'properties': {}}},
    189: {0: {'name': 'Fence (Birch)', 'properties': {}}},
    190: {0: {'name': 'Fence (Jungle)', 'properties': {}}},
    191: {0: {'name': 'Fence (Dark Oak)', 'properties': {}}},
    192: {0: {'name': 'Fence (Acacia)', 'properties': {}}},
    193: {0: {'name': 'Wooden Door Block (Spruce)', 'properties': {}}},
    194: {0: {'name': 'Wooden Door Block (Birch)', 'properties': {}}},
    195: {0: {'name': 'Wooden Door Block (Jungle)', 'properties': {}}},
    196: {0: {'name': 'Wooden Door Block (Acacia)', 'properties': {}}},
    197: {0: {'name': 'Wooden Door Block (Dark Oak)', 'properties': {}}},
    198: {0: {'name': 'End rod', 'properties': {}}},
    199: {0: {'name': 'Chorus Plant', 'properties': {}}},
    200: {0: {'name': 'Chorus Flower', 'properties': {}}},
    201: {0: {'name': 'Purpur Block', 'properties': {}}},
    202: {0: {'name': 'Purpur Pillar', 'properties': {}}},
    203: {0: {'name': 'Purpur Stairs', 'properties': {}}},
    204: {0: {'name': 'Purpur Slab (Double)', 'properties': {}}},
    205: {0: {'name': 'Purpur Slab', 'properties': {}}},
    206: {0: {'name': 'End Stone Bricks', 'properties': {}}},
    208: {0: {'name': 'Grass Path', 'properties': {}}},
    209: {0: {'name': 'End Gateway', 'properties': {}}},
    212: {0: {'name': 'Frosted Ice', 'properties': {}}},
    213: {0: {'name': 'Magma Block', 'properties': {}}},
    214: {0: {'name': 'Nether Wart (Block)', 'properties': {}}},
    215: {0: {'name': 'Nether Brick (Red)', 'properties': {}}},
    216: {0: {'name': 'Bone Block', 'properties': {}}},
    218: {0: {'name': 'Observer', 'properties': {}}},
    229: {0: {'name': 'Shulker Box (Purple)', 'properties': {}}},
    255: {0: {'name': 'Structure Block', 'properties': {}}},
    256: {0: {'name': 'Iron Shovel', 'properties': {}}},
    257: {0: {'name': 'Iron Pickaxe', 'properties': {}}},
    258: {0: {'name': 'Iron Axe', 'properties': {}}},
    259: {0: {'name': 'Flint and Steel', 'properties': {}}},
    260: {0: {'name': 'Apple', 'properties': {}}},
    261: {0: {'name': 'Bow', 'properties': {}}},
    262: {0: {'name': 'Arrow', 'properties': {}}},
    263: {0: {'name': 'Coal', 'properties': {}},
          1: {'name': 'Charcoal', 'properties': {}}},
    264: {0: {'name': 'Diamond Gem', 'properties': {}}},
    265: {0: {'name': 'Iron Ingot', 'properties': {}}},
    266: {0: {'name': 'Gold Ingot', 'properties': {}}},
    267: {0: {'name': 'Iron Sword', 'properties': {}}},
    268: {0: {'name': 'Wooden Sword', 'properties': {}}},
    269: {0: {'name': 'Wooden Shovel', 'properties': {}}},
    270: {0: {'name': 'Wooden Pickaxe', 'properties': {}}},
    271: {0: {'name': 'Wooden Axe', 'properties': {}}},
    272: {0: {'name': 'Stone Sword', 'properties': {}}},
    273: {0: {'name': 'Stone Shovel', 'properties': {}}},
    274: {0: {'name': 'Stone Pickaxe', 'properties': {}}},
    275: {0: {'name': 'Stone Axe', 'properties': {}}},
    276: {0: {'name': 'Diamond Sword', 'properties': {}}},
    277: {0: {'name': 'Diamond Shovel', 'properties': {}}},
    278: {0: {'name': 'Diamond Pickaxe', 'properties': {}}},
    279: {0: {'name': 'Diamond Axe', 'properties': {}}},
    280: {0: {'name': 'Stick', 'properties': {}}},
    281: {0: {'name': 'Bowl', 'properties': {}}},
    282: {0: {'name': 'Mushroom Stew', 'properties': {}}},
    283: {0: {'name': 'Gold Sword', 'properties': {}}},
    284: {0: {'name': 'Gold Shovel', 'properties': {}}},
    285: {0: {'name': 'Gold Pickaxe', 'properties': {}}},
    286: {0: {'name': 'Gold Axe', 'properties': {}}},
    287: {0: {'name': 'String', 'properties': {}}},
    288: {0: {'name': 'Feather', 'properties': {}}},
    289: {0: {'name': 'Gunpowder', 'properties': {}}},
    290: {0: {'name': 'Wooden Hoe', 'properties': {}}},
    291: {0: {'name': 'Stone Hoe', 'properties': {}}},
    292: {0: {'name': 'Iron Hoe', 'properties': {}}},
    293: {0: {'name': 'Diamond Hoe', 'properties': {}}},
    294: {0: {'name': 'Gold Hoe', 'properties': {}}},
    295: {0: {'name': 'Wheat Seeds', 'properties': {}}},
    296: {0: {'name': 'Wheat', 'properties': {}}},
    297: {0: {'name': 'Bread', 'properties': {}}},
    298: {0: {'name': 'Leather Helmet', 'properties': {}}},
    299: {0: {'name': 'Leather Chestplate', 'properties': {}}},
    300: {0: {'name': 'Leather Leggings', 'properties': {}}},
    301: {0: {'name': 'Leather Boots', 'properties': {}}},
    302: {0: {'name': 'Chainmail Helmet', 'properties': {}}},
    303: {0: {'name': 'Chainmail Chestplate', 'properties': {}}},
    304: {0: {'name': 'Chainmail Leggings', 'properties': {}}},
    305: {0: {'name': 'Chainmail Boots', 'properties': {}}},
    306: {0: {'name': 'Iron Helmet', 'properties': {}}},
    307: {0: {'name': 'Iron Chestplate', 'properties': {}}},
    308: {0: {'name': 'Iron Leggings', 'properties': {}}},
    309: {0: {'name': 'Iron Boots', 'properties': {}}},
    310: {0: {'name': 'Diamond Helmet', 'properties': {}}},
    311: {0: {'name': 'Diamond Chestplate', 'properties': {}}},
    312: {0: {'name': 'Diamond Leggings', 'properties': {}}},
    313: {0: {'name': 'Diamond Boots', 'properties': {}}},
    314: {0: {'name': 'Gold Helmet', 'properties': {}}},
    315: {0: {'name': 'Gold Chestplate', 'properties': {}}},
    316: {0: {'name': 'Gold Leggings', 'properties': {}}},
    317: {0: {'name': 'Gold Boots', 'properties': {}}},
    318: {0: {'name': 'Flint', 'properties': {}}},
    319: {0: {'name': 'Raw Porkchop', 'properties': {}}},
    320: {0: {'name': 'Cooked Porkchop', 'properties': {}}},
    321: {0: {'name': 'Painting', 'properties': {}}},
    322: {0: {'name': 'Golden Apple', 'properties': {}},
          1: {'name': 'Enchanted Golden Apple', 'properties': {}}},
    323: {0: {'name': 'Sign', 'properties': {}}},
    324: {0: {'name': 'Wooden Door', 'properties': {}}},
    325: {0: {'name': 'Bucket', 'properties': {}}},
    326: {0: {'name': 'Bucket (Water)', 'properties': {}}},
    327: {0: {'name': 'Bucket (Lava)', 'properties': {}}},
    328: {0: {'name': 'Minecart', 'properties': {}}},
    329: {0: {'name': 'Saddle', 'properties': {}}},
    330: {0: {'name': 'Iron Door', 'properties': {}}},
    331: {0: {'name': 'Redstone Dust', 'properties': {}}},
    332: {0: {'name': 'Snowball', 'properties': {}}},
    333: {0: {'name': 'Boat', 'properties': {}}},
    334: {0: {'name': 'Leather', 'properties': {}}},
    335: {0: {'name': 'Bucket (Milk)', 'properties': {}}},
    336: {0: {'name': 'Clay Brick', 'properties': {}}},
    337: {0: {'name': 'Clay', 'properties': {}}},
    338: {0: {'name': 'Sugar Cane', 'properties': {}}},
    339: {0: {'name': 'Paper', 'properties': {}}},
    340: {0: {'name': 'Book', 'properties': {}}},
    341: {0: {'name': 'Slime Ball', 'properties': {}}},
    342: {0: {'name': 'Minecart (Storage)', 'properties': {}}},
    343: {0: {'name': 'Minecart (Powered)', 'properties': {}}},
    344: {0: {'name': 'Egg', 'properties': {}}},
    345: {0: {'name': 'Compass', 'properties': {}}},
    346: {0: {'name': 'Fishing Rod', 'properties': {}}},
    347: {0: {'name': 'Watch', 'properties': {}}},
    348: {0: {'name': 'Glowstone Dust', 'properties': {}}},
    349: {0: {'name': 'Raw Fish', 'properties': {}},
          1: {'name': 'Raw Salmon', 'properties': {}},
          2: {'name': 'Clownfish', 'properties': {}},
          3: {'name': 'Pufferfish', 'properties': {}}},
    350: {0: {'name': 'Cooked Fish', 'properties': {}},
          1: {'name': 'Cooked Salmon', 'properties': {}},
          2: {'name': 'Clownfish', 'properties': {}},
          3: {'name': 'Pufferfish', 'properties': {}}},
    351: {0: {'name': 'Ink Sack', 'properties': {}},
          1: {'name': 'Rose Red Dye', 'properties': {}},
          2: {'name': 'Cactus Green Dye', 'properties': {}},
          3: {'name': 'Cocoa Bean', 'properties': {}},
          4: {'name': 'Lapis Lazuli', 'properties': {}},
          5: {'name': 'Purple Dye', 'properties': {}},
          6: {'name': 'Cyan Dye', 'properties': {}},
          7: {'name': 'Light Gray Dye', 'properties': {}},
          8: {'name': 'Gray Dye', 'properties': {}},
          9: {'name': 'Pink Dye', 'properties': {}},
          10: {'name': 'Lime Dye', 'properties': {}},
          11: {'name': 'Dandelion Yellow Dye', 'properties': {}},
          12: {'name': 'Light Blue Dye', 'properties': {}},
          13: {'name': 'Magenta Dye', 'properties': {}},
          14: {'name': 'Orange Dye', 'properties': {}},
          15: {'name': 'Bone Meal', 'properties': {}}},
    352: {0: {'name': 'Bone', 'properties': {}}},
    353: {0: {'name': 'Sugar', 'properties': {}}},
    354: {0: {'name': 'Cake', 'properties': {}}},
    355: {0: {'name': 'Bed', 'properties': {}}},
    356: {0: {'name': 'Redstone Repeater', 'properties': {}}},
    357: {0: {'name': 'Cookie', 'properties': {}}},
    358: {0: {'name': 'Map', 'properties': {}}},
    359: {0: {'name': 'Shears', 'properties': {}}},
    360: {0: {'name': 'Melon (Slice)', 'properties': {}}},
    361: {0: {'name': 'Pumpkin Seeds', 'properties': {}}},
    362: {0: {'name': 'Melon Seeds', 'properties': {}}},
    363: {0: {'name': 'Raw Beef', 'properties': {}}},
    364: {0: {'name': 'Steak', 'properties': {}}},
    365: {0: {'name': 'Raw Chicken', 'properties': {}}},
    366: {0: {'name': 'Cooked Chicken', 'properties': {}}},
    367: {0: {'name': 'Rotten Flesh', 'properties': {}}},
    368: {0: {'name': 'Ender Pearl', 'properties': {}}},
    369: {0: {'name': 'Blaze Rod', 'properties': {}}},
    370: {0: {'name': 'Ghast Tear', 'properties': {}}},
    371: {0: {'name': 'Gold Nugget', 'properties': {}}},
    372: {0: {'name': 'Nether Wart Seeds', 'properties': {}}},
    373: {0: {'name': 'Water Bottle', 'properties': {}},
          16: {'name': 'Awkward Potion', 'properties': {}},
          32: {'name': 'Thick Potion', 'properties': {}},
          64: {'name': 'Mundane Potion', 'properties': {}},
          8193: {'name': 'Regeneration Potion (0:45)', 'properties': {}},
          8194: {'name': 'Swiftness Potion (3:00)', 'properties': {}},
          8195: {'name': 'Fire Resistance Potion (3:00)', 'properties': {}},
          8196: {'name': 'Poison Potion (0:45)', 'properties': {}},
          8197: {'name': 'Healing Potion', 'properties': {}},
          8198: {'name': 'Night Vision Potion (3:00)', 'properties': {}},
          8200: {'name': 'Weakness Potion (1:30)', 'properties': {}},
          8201: {'name': 'Strength Potion (3:00)', 'properties': {}},
          8202: {'name': 'Slowness Potion (1:30)', 'properties': {}},
          8204: {'name': 'Harming Potion', 'properties': {}},
          8205: {'name': 'Water Breathing Potion (3:00)', 'properties': {}},
          8206: {'name': 'Invisibility Potion (3:00)', 'properties': {}},
          8225: {'name': 'Regeneration Potion II (0:22)', 'properties': {}},
          8226: {'name': 'Swiftness Potion II (1:30)', 'properties': {}},
          8228: {'name': 'Poison Potion II (0:22)', 'properties': {}},
          8229: {'name': 'Healing Potion II', 'properties': {}},
          8233: {'name': 'Strength Potion II (1:30)', 'properties': {}},
          8235: {'name': 'Leaping Potion II (1:30)', 'properties': {}},
          8236: {'name': 'Harming Potion II', 'properties': {}},
          8257: {'name': 'Regeneration Potion (2:00)', 'properties': {}},
          8258: {'name': 'Swiftness Potion (8:00)', 'properties': {}},
          8259: {'name': 'Fire Resistance Potion (8:00)', 'properties': {}},
          8260: {'name': 'Poison Potion (2:00)', 'properties': {}},
          8262: {'name': 'Night Vision Potion (8:00)', 'properties': {}},
          8264: {'name': 'Weakness Potion (4:00)', 'properties': {}},
          8265: {'name': 'Strength Potion (8:00)', 'properties': {}},
          8266: {'name': 'Slowness Potion (4:00)', 'properties': {}},
          8267: {'name': 'Leaping Potion (3:00)', 'properties': {}},
          8269: {'name': 'Water Breathing Potion (8:00)', 'properties': {}},
          8270: {'name': 'Invisibility Potion (8:00)', 'properties': {}},
          8289: {'name': 'Regeneration Potion II (1:00)', 'properties': {}},
          8290: {'name': 'Swiftness Potion II (4:00)', 'properties': {}},
          8292: {'name': 'Poison Potion II (1:00)', 'properties': {}},
          8297: {'name': 'Strength Potion II (4:00)', 'properties': {}},
          16385: {'name': 'Regeneration Splash (0:33)', 'properties': {}},
          16386: {'name': 'Swiftness Splash (2:15)', 'properties': {}},
          16387: {'name': 'Fire Resistance Splash (2:15)', 'properties': {}},
          16388: {'name': 'Poison Splash (0:33)', 'properties': {}},
          16389: {'name': 'Healing Splash', 'properties': {}},
          16390: {'name': 'Night Vision Splash (2:15)', 'properties': {}},
          16392: {'name': 'Weakness Splash (1:07)', 'properties': {}},
          16393: {'name': 'Strength Splash (2:15)', 'properties': {}},
          16394: {'name': 'Slowness Splash (1:07)', 'properties': {}},
          16396: {'name': 'Harming Splash', 'properties': {}},
          16397: {'name': 'Breathing Splash (2:15)', 'properties': {}},
          16398: {'name': 'Invisibility Splash (2:15)', 'properties': {}},
          16417: {'name': 'Regeneration Splash II (0:16)', 'properties': {}},
          16418: {'name': 'Swiftness Splash II (1:07)', 'properties': {}},
          16420: {'name': 'Poison Splash II (0:16)', 'properties': {}},
          16421: {'name': 'Healing Splash II', 'properties': {}},
          16425: {'name': 'Strength Splash II (1:07)', 'properties': {}},
          16427: {'name': 'Leaping Splash II (1:07)', 'properties': {}},
          16428: {'name': 'Harming Splash II', 'properties': {}},
          16449: {'name': 'Regeneration Splash (1:30)', 'properties': {}},
          16450: {'name': 'Swiftness Splash (6:00)', 'properties': {}},
          16451: {'name': 'Fire Resistance Splash (6:00)', 'properties': {}},
          16452: {'name': 'Poison Splash (1:30)', 'properties': {}},
          16454: {'name': 'Night Vision Splash (6:00)', 'properties': {}},
          16456: {'name': 'Weakness Splash (3:00)', 'properties': {}},
          16457: {'name': 'Strength Splash (6:00)', 'properties': {}},
          16458: {'name': 'Slowness Splash (3:00)', 'properties': {}},
          16459: {'name': 'Leaping Splash (2:15)', 'properties': {}},
          16461: {'name': 'Breathing Splash (6:00)', 'properties': {}},
          16462: {'name': 'Invisibility Splash (6:00)', 'properties': {}},
          16481: {'name': 'Regeneration Splash II (0:45)', 'properties': {}},
          16482: {'name': 'Swiftness Splash II (3:00)', 'properties': {}},
          16484: {'name': 'Poison Splash II (0:45)', 'properties': {}},
          16489: {'name': 'Strength Splash II (3:00)', 'properties': {}}},
    374: {0: {'name': 'Glass Bottle', 'properties': {}}},
    375: {0: {'name': 'Spider Eye', 'properties': {}}},
    376: {0: {'name': 'Fermented Spider Eye', 'properties': {}}},
    377: {0: {'name': 'Blaze Powder', 'properties': {}}},
    378: {0: {'name': 'Magma Cream', 'properties': {}}},
    379: {0: {'name': 'Brewing Stand', 'properties': {}}},
    380: {0: {'name': 'Cauldron', 'properties': {}}},
    381: {0: {'name': 'Eye of Ender', 'properties': {}}},
    382: {0: {'name': 'Glistering Melon (Slice)', 'properties': {}}},
    383: {50: {'name': 'Spawn Egg (Creeper)', 'properties': {}},
          51: {'name': 'Spawn Egg (Skeleton)', 'properties': {}},
          52: {'name': 'Spawn Egg (Spider)', 'properties': {}},
          54: {'name': 'Spawn Egg (Zombie)', 'properties': {}},
          55: {'name': 'Spawn Egg (Slime)', 'properties': {}},
          56: {'name': 'Spawn Egg (Ghast)', 'properties': {}},
          57: {'name': 'Spawn Egg (Zombie Pigmen)', 'properties': {}},
          58: {'name': 'Spawn Egg (Endermen)', 'properties': {}},
          59: {'name': 'Spawn Egg (Cave Spider)', 'properties': {}},
          60: {'name': 'Spawn Egg (Silverfish)', 'properties': {}},
          61: {'name': 'Spawn Egg (Blaze)', 'properties': {}},
          62: {'name': 'Spawn Egg (Magma Cube)', 'properties': {}},
          65: {'name': 'Spawn Egg (Bat)', 'properties': {}},
          66: {'name': 'Spawn Egg (Witch)', 'properties': {}},
          67: {'name': 'Spawn Egg (Endermite)', 'properties': {}},
          68: {'name': 'Spawn Egg (Guardian)', 'properties': {}},
          69: {'name': 'Spawn Egg (Shulker)', 'properties': {}},
          90: {'name': 'Spawn Egg (Pig)', 'properties': {}},
          91: {'name': 'Spawn Egg (Sheep)', 'properties': {}},
          92: {'name': 'Spawn Egg (Cow)', 'properties': {}},
          93: {'name': 'Spawn Egg (Chicken)', 'properties': {}},
          94: {'name': 'Spawn Egg (Squid)', 'properties': {}},
          95: {'name': 'Spawn Egg (Wolf)', 'properties': {}},
          96: {'name': 'Spawn Egg (Mooshroom)', 'properties': {}},
          98: {'name': 'Spawn Egg (Ocelot)', 'properties': {}},
          100: {'name': 'Spawn Egg (Horse)', 'properties': {}},
          101: {'name': 'Spawn Egg (Rabbit)', 'properties': {}},
          102: {'name': 'Spawn Egg (Polar Bear)', 'properties': {}},
          120: {'name': 'Spawn Egg (Villager)', 'properties': {}}},
    384: {0: {'name': 'Bottle of Enchanting', 'properties': {}}},
    385: {0: {'name': 'Fire Charge', 'properties': {}}},
    386: {0: {'name': 'Book and Quill', 'properties': {}}},
    387: {0: {'name': 'Written Book', 'properties': {}}},
    388: {0: {'name': 'Emerald', 'properties': {}}},
    389: {0: {'name': 'Item Frame', 'properties': {}}},
    390: {0: {'name': 'Flower Pot', 'properties': {}}},
    391: {0: {'name': 'Carrot', 'properties': {}}},
    392: {0: {'name': 'Potato', 'properties': {}}},
    393: {0: {'name': 'Baked Potato', 'properties': {}}},
    394: {0: {'name': 'Poisonous Potato', 'properties': {}}},
    395: {0: {'name': 'Empty Map', 'properties': {}}},
    396: {0: {'name': 'Golden Carrot', 'properties': {}}},
    397: {0: {'name': 'Head (Skeleton)', 'properties': {}},
          1: {'name': 'Head (Wither)', 'properties': {}},
          2: {'name': 'Head (Zombie)', 'properties': {}},
          3: {'name': 'Head (Steve)', 'properties': {}},
          4: {'name': 'Head (Creeper)', 'properties': {}}},
    398: {0: {'name': 'Carrot on a Stick', 'properties': {}}},
    399: {0: {'name': 'Nether Star', 'properties': {}}},
    400: {0: {'name': 'Pumpkin Pie', 'properties': {}}},
    401: {0: {'name': 'Firework Rocket', 'properties': {}}},
    402: {0: {'name': 'Firework Star', 'properties': {}}},
    403: {0: {'name': 'Enchanted Book', 'properties': {}}},
    404: {0: {'name': 'Redstone Comparator', 'properties': {}}},
    405: {0: {'name': 'Nether Brick (Item)', 'properties': {}}},
    406: {0: {'name': 'Nether Quartz', 'properties': {}}},
    407: {0: {'name': 'Minecart (TNT)', 'properties': {}}},
    408: {0: {'name': 'Minecart (Hopper)', 'properties': {}}},
    409: {0: {'name': 'Prismarine Shard', 'properties': {}}},
    410: {0: {'name': 'Prismarine Crystals', 'properties': {}}},
    411: {0: {'name': 'Raw Rabbit', 'properties': {}}},
    412: {0: {'name': 'Cooked Rabbit', 'properties': {}}},
    413: {0: {'name': 'Rabbit Stew', 'properties': {}}},
    414: {0: {'name': "Rabbit's Foot", 'properties': {}}},
    415: {0: {'name': 'Rabbit Hide', 'properties': {}}},
    416: {0: {'name': 'Armor Stand', 'properties': {}}},
    417: {0: {'name': 'Iron Horse Armor', 'properties': {}}},
    418: {0: {'name': 'Gold Horse Armor', 'properties': {}}},
    419: {0: {'name': 'Diamond Horse Armor', 'properties': {}}},
    420: {0: {'name': 'Lead', 'properties': {}}},
    421: {0: {'name': 'Name Tag', 'properties': {}}},
    422: {0: {'name': 'Minecart (Command Block)', 'properties': {}}},
    423: {0: {'name': 'Raw Mutton', 'properties': {}}},
    424: {0: {'name': 'Cooked Mutton', 'properties': {}}},
    425: {0: {'name': 'Banner (Black)', 'properties': {}},
          1: {'name': 'Banner (Red)', 'properties': {}},
          2: {'name': 'Banner (Green)', 'properties': {}},
          3: {'name': 'Banner (Brown)', 'properties': {}},
          4: {'name': 'Banner (Blue)', 'properties': {}},
          5: {'name': 'Banner (Purple)', 'properties': {}},
          6: {'name': 'Banner (Cyan)', 'properties': {}},
          7: {'name': 'Banner (Light Gray)', 'properties': {}},
          8: {'name': 'Banner (Gray)', 'properties': {}},
          9: {'name': 'Banner (Pink)', 'properties': {}},
          10: {'name': 'Banner (Lime)', 'properties': {}},
          11: {'name': 'Banner (Yellow)', 'properties': {}},
          12: {'name': 'Banner (Light Blue)', 'properties': {}},
          13: {'name': 'Banner (Magenta)', 'properties': {}},
          14: {'name': 'Banner (Orange)', 'properties': {}},
          15: {'name': 'Banner (White)', 'properties': {}}},
    426: {0: {'name': 'End Crystal', 'properties': {}}},
    427: {0: {'name': 'Wooden Door (Spruce)', 'properties': {}}},
    428: {0: {'name': 'Wooden Door (Birch)', 'properties': {}}},
    429: {0: {'name': 'Wooden Door (Jungle)', 'properties': {}}},
    430: {0: {'name': 'Wooden Door (Acacia)', 'properties': {}}},
    431: {0: {'name': 'Wooden Door (Dark Oak)', 'properties': {}}},
    432: {0: {'name': 'Chorus Fruit', 'properties': {}}},
    433: {0: {'name': 'Chorus Fruit (Popped)', 'properties': {}}},
    434: {0: {'name': 'Beetroot', 'properties': {}}},
    435: {0: {'name': 'Beetroot Seeds', 'properties': {}}},
    436: {0: {'name': 'Beetroot Soup', 'properties': {}}},
    437: {0: {'name': "Dragon's Breath", 'properties': {}}},
    439: {0: {'name': 'Arrow (Spectral)', 'properties': {}}},
    442: {0: {'name': 'Shield', 'properties': {}}},
    443: {0: {'name': 'Elytra', 'properties': {}}},
    449: {0: {'name': 'Totem of Undying', 'properties': {}}},
    450: {0: {'name': 'Shulker Shell', 'properties': {}}},
    2256: {0: {'name': 'Music Disk (13)', 'properties': {}}},
    2257: {0: {'name': 'Music Disk (Cat)', 'properties': {}}},
    2258: {0: {'name': 'Music Disk (Blocks)', 'properties': {}}},
    2259: {0: {'name': 'Music Disk (Chirp)', 'properties': {}}},
    2260: {0: {'name': 'Music Disk (Far)', 'properties': {}}},
    2261: {0: {'name': 'Music Disk (Mall)', 'properties': {}}},
    2262: {0: {'name': 'Music Disk (Mellohi)', 'properties': {}}},
    2263: {0: {'name': 'Music Disk (Stal)', 'properties': {}}},
    2264: {0: {'name': 'Music Disk (Strad)', 'properties': {}}},
    2265: {0: {'name': 'Music Disk (Ward)', 'properties': {}}},
    2266: {0: {'name': 'Music Disk (11)', 'properties': {}}},
    2267: {0: {'name': 'Music Disk (Wait)', 'properties': {}}}}
