"""Packet name, packet id: <hex byte value in two's complement>"""
PACKET_NAME: (str, int) = {
    "HANDSHAKE":                     0x00,
    "LOGIN_START":                   0x00,
    "TELEPORT_CONFIRM":              0x00,
    "DISCONNECT_LOGIN":              0x00,
    "CHAT_MESSAGE_SERVERBOUND":      0x02,
    "LOGIN_SUCCESS":                 0x02,
    "SET_COMPRESSION":               0x03,
    "CLIENT_STATUS":                 0x03,
    "CLIENT_SETTINGS":               0x04,
    "PLUGIN_MESSAGE_SERVERBOUND":    0x09,
    "KEEP_ALIVE_SERVERBOUND":        0x0B,
    "CHAT_MESSAGE_CLIENTBOUND":      0x0F,
    "OPEN_WINDOW":                   0x13,
    "PLUGIN_MESSAGE_CLIENTBOUND":    0x18,
    "DISCONNECT_PLAY":               0x1A,
    "CHANGE_GAME_STATE":             0x1E,
    "KEEP_ALIVE_CLIENTBOUND":        0x1F,
    "JOIN_GAME":                     0x23,
    "PLAYER_POSITION_AND_LOOK":      0x2F,
    "RESPAWN":                       0x35,
    "PLAYER_LIST_HEADER_AND_FOOTER": 0x4A,
}
