"""Provide functions to allow creating clientbound packets."""
from versions.v1_12_2.packet.clientbound import login, play

packets_specifics = {
    "login": {
        0: login.Disconnect(),
        # 1: Clientbound.EncryptionRequest(),
        2: login.LoginSuccess(),
        3: login.SetCompression(),
    },
    "play": {
        # 0x00: play.SpawnObject(),
        # 0x01: play.SpawnExperienceOrb(),
        # 0x02: play.SpawnGlobalEntity(),
        # 0x03: play.SpawnMob(),
        # 0x04: play.SpawnPainting(),
        # 0x05: play.SpawnPlayer(),
        # 0x06: play.Animation(),
        # 0x07: play.Statistics(),
        # 0x08: play.BlockBreakAnimation(),
        # 0x09: play.UpdateBlockEntity(),
        # 0x0A: play.BlockAction(),
        0x0B: play.BlockChange(),
        # 0x0C: play.BossBar(),
        0x0D: play.ServerDifficulty(),
        # 0x0E: play.TabComplete(),
        0x0F: play.ChatMessage(),  # TODO: improve or sth
        # 0x10: play.MultiBlockChange(),
        # 0x11: play.ConfirmTransaction(),
        # 0x12: play.CloseWindow(),
        # 0x13: play.OpenWindow(),
        # 0x14: play.WindowItems(),
        # 0x15: play.WindowProperty(),
        # 0x16: play.SetSlot(),
        # 0x17: play.SetCooldown(),
        # 0x18: play.PluginMessage(),
        # 0x19: play.NamedSoundEffect(),
        0x1A: play.Disconnect(),
        0x1B: play.EntityStatus(),
        # 0x1C: play.Explosion(),
        # 0x1D: play.UnloadChunk(),
        0x1E: play.ChangeGameState(),
        0x1F: play.KeepAlive(),
        0x20: play.ChunkData(),
        # 0x21: play.Effect(),
        # 0x22: play.Particle(),
        0x23: play.JoinGame(),
        # 0x24: play.Map(),
        # 0x25: play.Entity(),
        # 0x26: play.EntityRelativeMove(),
        # 0x27: play.EntityLookAndRelativeMove(),
        # 0x28: play.EntityLook(),
        # 0x29: play.VehicleMove(),
        # 0x2A: play.OpenSignEditor(),
        # 0x2B: play.CraftRecipeResponse(),
        0x2C: play.PlayerAbilities(),
        0x2D: play.CombatEvent(),
        # 0x2E: play.PlayerListItem(),
        0x2F: play.PlayerPositionAndLook(),
        # 0x30: play.UseBed(),
        # 0x31: play.UnlockRecipes(),
        # 0x32: play.DestroyEntities(),
        # 0x33: play.RemoveEntityEffect(),
        # 0x34: play.ResourcePackSend(),
        0x35: play.Respawn(),
        # 0x36: play.EntityHeadLook(),
        # 0x37: play.SelectAdvancementTab(),
        # 0x38: play.WorldBorder(),
        # 0x39: play.Camera(),
        # 0x3A: play.HeldItemChange(),
        # 0x3B: play.DisplayScoreboard(),
        # 0x3C: play.EntityMetadata(),
        # 0x3D: play.AttachEntity(),
        # 0x3E: play.EntityVelocity(),
        # 0x3F: play.EntityEquipment(),
        # 0x40: play.SetExperience(),
        0x41: play.UpdateHealth(),
        # 0x42: play.ScoreboardObjective(),
        # 0x43: play.SetPassengers(),
        # 0x44: play.Teams(),
        # 0x45: play.UpdateScore(),
        0x46: play.SpawnPosition(),
        # 0x47: play.TimeUpdate(),
        # 0x48: play.Title(),
        # 0x49: play.SoundEffect(),
        # 0x4A: play.PlayerListHeaderAndFooter(),
        # 0x4B: play.CollectItem(),
        # 0x4C: play.EntityTeleport(),
        # 0x4D: play.Advancements(),
        # 0x4E: play.EntityProperties(),
        # 0x4F: play.EntityEffect(),
    }
}